apiVersion: v1
kind: Service
metadata:
{{- if .Values.client.service.servicename }}
  name: {{ .Values.client.service.servicename }}
{{- else }}
  name: {{ include "multi-k8s.fullname" . }}
{{- end}}
  namespace: {{ .Values.app.namespace }}
spec:
  type: {{ .Values.client.service.type }}
  {{- if eq .Values.client.service.type "ClusterIP" }}
  {{- if .Values.client.service.clusterIP }}
  clusterIP: {{ .Values.client.service.clusterIP }}
  {{- end }}
  {{- end }}
  selector:
    component: {{ .Values.client.labels }}
  ports:
   - port: {{ .Values.client.service.externalPort }}
{{- if (and (eq .Values.client.service.type "NodePort") (not (empty .Values.client.service.nodePort))) }}
     nodePort: {{.Values.client.service.nodePort}}
{{- end }}
     targetPort: {{ .Values.client.service.internalPort }}
     protocol: {{ .Values.client.service.protocol }}
     name: {{ .Values.client.service.portName }}       
