apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: {{ .Values.app.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
   - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: {{ .Values.client.service.servicename }}
              servicePort: {{ .Values.client.service.externalPort }}
          - path: /api/?(.*)
            backend:
              serviceName: {{ .Values.server.service.servicename }}
              servicePort: {{ .Values.server.service.externalPort }}
