apiVersion: v1
kind: Service
metadata:
{{- if .Values.postgres.service.servicename }}
  name: {{ .Values.postgres.service.servicename }}
{{- else }}
  name: postgres-{{ include "multi-k8s.fullname" . }}
{{- end}}
  namespace: {{ .Values.app.namespace }}
spec:
  type: {{ .Values.postgres.service.type }}
  {{- if eq .Values.postgres.service.type "ClusterIP" }}
  {{- if .Values.postgres.service.clusterIP }}
  clusterIP: {{ .Values.postgres.service.clusterIP }}
  {{- end }}
  {{- end }}
  selector:
    component: {{ .Values.postgres.labels }}
  ports:
    - port: {{ .Values.postgres.service.externalPort }}
      targetPort: {{ .Values.postgres.service.internalPort }}
{{- if (and (eq .Values.postgres.service.type "NodePort") (not (empty .Values.postgres.service.nodePort))) }}
      nodePort: {{ .Values.postgres.service.nodePort }}
{{- end }}      
      name: {{ .Values.postgres.service.portName }}
