apiVersion: v1
kind: Secret
metadata:
{{- $secret_name := "pgpassword" }}
  name: {{ $secret_name }}
  namespace: {{ .Values.app.namespace }}
data:
{{- range $name, $value := .Values.postgres.secret.env }}
{{- if not (empty $value) }}
{{- if eq $name "PGPASSWORD" }}
  {{ $name }}: {{ $value | b64enc}}
{{- end }}
{{- end }}
{{- end }}
