apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.worker.labels }}
  template:
    metadata:
      labels:
        component: {{ .Values.worker.labels }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.app.imagePullSecret }}
      containers:
        - name: {{ .Values.worker.containers.name }}
          image: "{{ .Values.worker.containers.image.name }}:{{ .Values.worker.containers.image.tag }}"
          {{- with .Values.worker.resources }}
          resources:
{{ toYaml . | indent 12 }}
        {{- end }}
          env:
          {{- range $name, $value := .Values.worker.env.redis }}
{{- if not (empty $value) }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
{{- end }}
{{- end }}
      
    
  
